services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: serverpod_sentinel
      POSTGRES_PASSWORD: "T2iL8hIJwV33SOLneL8Po8HKCAwchje2"
    volumes:
      - serverpod_sentinel_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "drj9_Fqc0mZvhNK9KTs-907ss-r7OfmH"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: serverpod_sentinel_test
      POSTGRES_PASSWORD: "JT07SLAaY1JopN0z9V74HlErfyRCMRIX"
    volumes:
      - serverpod_sentinel_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "xSRLk7ECNs3lWznaRnIZeSEWKgb70KiX"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  serverpod_sentinel_data:
  serverpod_sentinel_test_data:
