name: serverpod_sentinel_server
description: Starting point for a Serverpod server.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod: 3.1.1
  serverpod_auth_idp_server: 3.1.1

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  serverpod_test: 3.1.1
  test: ^1.25.5


serverpod:
  scripts:
    start: dart bin/main.dart --apply-migrations

    flutter_build: cd ../serverpod_sentinel_flutter && flutter build web --base-href /app/ --wasm && IF NOT EXIST ..\serverpod_sentinel_server\web\app\ md ..\serverpod_sentinel_server\web\app\ && rmdir /s /q ..\serverpod_sentinel_server\web\app\ && robocopy build/web/ ../serverpod_sentinel_server/web/app
